### ISSUE TITLE
弱弱地请教 config在哪里设置

### ISSUE THREAD

**Issue by oozry12** [wsdo/vscode-markdown-img-qiniu#13]
{
    "qiniu.access_key": "*******************",
    "qiniu.secret_key": "*******************",
    "qiniu.bucket": "static",
    "qiniu.remotePath": "shudong/${fileName}",
    "qiniu.domain": "http://s.shudong.wang"
}

**Comment by wsdo** [comment]
打开配置，搜 json ，点击json 编辑，把自己的配置贴进去

**Comment by oozry12** [comment]
感谢开发者耐心
